Update README.md
PoCInnovation/orbit-db-cli pull request #4
Opened 2023-04-13 16:16 UTC by YlanGarnier

# Description

Updated Readme to be up to date with S1 2023 working team
Related to #1

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to an issue
- [x] I have linked this PR to a milestone
- [x] I have linked this PR to a project
- [x] I have updated the README and other relevant documents (guides...)

2023-04-14 17:21 UTC, RezaRahemtola requested changes

2023-04-14 17:21 UTC, RezaRahemtola commented on README.md
> -| [<img src="https://github.com/adrienfort.png?size=85" width=85><br><sub>[Manager's name]</sub>](https://github.com/adrienfort)
You can remove the brackets around the names:\
`Ylan GARNIER` instead of `[Ylan GARNIER]` :wink:

2023-04-14 18:08 UTC, YlanGarnier commented on README.md
> -| [<img src="https://github.com/adrienfort.png?size=85" width=85><br><sub>[Manager's name]</sub>](https://github.com/adrienfort)
done :slightly_smiling_face:

2023-04-15 09:29 UTC, RezaRahemtola approved these changes
LGTM !

2023-04-15 09:30 UTC, RezaRahemtola commented
Just make sure to use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) next time @YlanGarnier :wink:

2023-04-15 09:31 UTC, merged